/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exception_teori;

import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/**
 *
 * @author ridho
 */
public class GUI_Eksepsi extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Eksepsi
     */
    Siswa siswa;
    public GUI_Eksepsi() {
        initComponents();
        siswa = new Siswa();
        txtmhske.setText("Masukan nilai mahasiswa ke "+String.valueOf(siswa.getNo()+1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmhske = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmhs1 = new javax.swing.JTextField();
        txtnilai = new javax.swing.JTextField();
        btn_proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memomhs = new javax.swing.JTextArea();
        btn_rata = new javax.swing.JButton();
        btn_tertinggi = new javax.swing.JButton();
        btn_terendah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtrata = new javax.swing.JLabel();
        txttinggi = new javax.swing.JLabel();
        txtrendah = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eksepsi Form");

        txtmhske.setText("Input Mahasiswa Ke 1");

        jLabel2.setText("Input Nilai");

        btn_proses.setText("Input Ke Textarea");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        memomhs.setColumns(20);
        memomhs.setRows(5);
        jScrollPane1.setViewportView(memomhs);

        btn_rata.setText("Rata Rata");
        btn_rata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rataActionPerformed(evt);
            }
        });

        btn_tertinggi.setText("Tertinggi");
        btn_tertinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tertinggiActionPerformed(evt);
            }
        });

        btn_terendah.setText("Terendah");
        btn_terendah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terendahActionPerformed(evt);
            }
        });

        jLabel3.setText("Rata Rata");

        jLabel4.setText("Tertinggi");

        jLabel5.setText("Terendah");

        txtrata.setText("0.0");

        txttinggi.setText("0");

        txtrendah.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("GUI Eksepsi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_proses))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_rata)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtrendah)
                                    .addComponent(txttinggi)
                                    .addComponent(txtrata)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_tertinggi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_terendah)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmhske)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtmhs1)
                                    .addComponent(txtnilai, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmhske)
                    .addComponent(txtmhs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_proses)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_rata)
                    .addComponent(btn_tertinggi)
                    .addComponent(btn_terendah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtrata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttinggi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtrendah))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_terendahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terendahActionPerformed
        txtrendah.setText(siswa.minNilai());
    }//GEN-LAST:event_btn_terendahActionPerformed

    private void btn_tertinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tertinggiActionPerformed
        txttinggi.setText(siswa.maxNilai());
    }//GEN-LAST:event_btn_tertinggiActionPerformed

    private void btn_rataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rataActionPerformed
        txtrata.setText(String.valueOf(siswa.rataRata()));
    }//GEN-LAST:event_btn_rataActionPerformed

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        try{
            String nm = txtmhs1.getText();
            int nl = Integer.parseInt(txtnilai.getText());
            if(nl < 0){
                throw new Exception("Tidak boleh bernilai negatif");
            } else if(nl > 100){
                throw new Exception("Tidak boleh melebihi 100");
            }else {
                siswa.insertData(nm, nl);
            }
        } catch(Exception s){
            JOptionPane.showMessageDialog(null, "terjadi kesalahan = "+s);
        }
        memomhs.setText("");
        for(int i = 0; i < siswa.getNo(); i++)
        {
            memomhs.append(String.valueOf(i+1));
            memomhs.append("     ");
            memomhs.append(siswa.getNama(i));
            memomhs.append("     ");
            memomhs.append(String.valueOf(siswa.getNilai(i)));
            memomhs.append("\n");
        }
        txtmhske.setText("Masukan nilai mahasiswa ke "+String.valueOf(siswa.getNo()+1));
    }//GEN-LAST:event_btn_prosesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Eksepsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Eksepsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Eksepsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Eksepsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Eksepsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_proses;
    private javax.swing.JButton btn_rata;
    private javax.swing.JButton btn_terendah;
    private javax.swing.JButton btn_tertinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea memomhs;
    private javax.swing.JTextField txtmhs1;
    private javax.swing.JLabel txtmhske;
    private javax.swing.JTextField txtnilai;
    private javax.swing.JLabel txtrata;
    private javax.swing.JLabel txtrendah;
    private javax.swing.JLabel txttinggi;
    // End of variables declaration//GEN-END:variables
}
